version: "3.3"

services:
  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: musicAppDB
      POSTGRES_DB: musicAppDB
      POSTGRES_PASS: musicAppDB
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/posgresql/data
    networks:
      - djangonetwork


  musical:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/musical
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - djangonetwork

networks:
    djangonetwork:
        driver: bridge