# Generated by Django 2.1.15 on 2022-04-30 19:53

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('iswc', models.CharField(max_length=11, unique=True, verbose_name='iswc')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('contributors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), size=None)),
            ],
        ),
    ]
